version: '3'

services:
  gift-list-service:
    build: ./gift-list-service/
    ports:
      - "4000:4000"
  gift-list-postgres:
    ports:
      - "5432:5432"
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password