version: '3'

services:
  gift-list-frontend:
    container_name: gift-list-frontend
    build:
      context: ./gift-list-frontend
      dockerfile: Dockerfile
    volumes:
      - './gift-list-frontend:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'
  gift-list-postgres:
    ports:
      - "5432:5432"
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password